body:
  - type: textarea
    attributes:
      label: End-result for the feature
      description: Describe the end-result that this feature helps achieve or the feature that you would like to see implemented.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Add any other information related to the change here. 
  - type: textarea
    attributes:
      label: Observations
      description: Add any observations or insights that you have about the feature here.
    validations:
      required: true
