# ISSUE_TEMPLATE/CONFIG.YML
contact_links:
  - name: 💡 Feature Request
    url: https://github.com/jgwill/o423/discussions/new?category=ideas
    about: Suggest any ideas you have for enhancing the Narrative Engine.
  - name: Creative Session Questions
    url: https://github.com/jgwill/o423/discussions/new?category=cquestions
  - name: 🤗 Get Help
    url: https://github.com/jgwill/o423/discussions/new?category=support
    about: If you encounter issues or need assistance, reach out through our discussion forums.
  - name: 📢 Community Chat
    url: https://discord.gg/narrative-continuity
    about: Join our Discord community to collaborate and discuss with other users.
  - name: 📬 Contact Support
    url: mailto:support@somedomain.com
    about: Directly contact our support team for urgent issues or inquiries.
